### PR TITLE
Add text models to tests

### PR DESCRIPTION
**Pull request by chungisaac**
Expanding the list of public models to test on. (text as input)

### CODE REVIEW

**Comment by nick-clarifai** [comment]
Models appear to be missing in dev/staging. `distilbart-cnn-12-6` wasn't found in either model (first one tried by pytest)

**Comment by chungisaac** [comment]
@nick-clarifai that's odd. here's what I see from dev and staging
```
api_dev=> select id from models where user_unique_id='distilbart-cnn-12-6';
                id                
----------------------------------
 184b06abb52c4813a6f4f360bc6eca21
(1 row)
```
and staging
```
api_staging=> select id from models where user_unique_id='distilbart-cnn-12-6';
                id                
----------------------------------
 f0c09fdc7c7e4168a3df9950559628ac
(1 row)
```

**Comment by Cjkjvfnby** [comment]
@chungisaac , I am not sure which id we currently use for the model, we have a bunch of them.

https://github.com/Clarifai/clarifai/blob/master/go/src/clarifai/db/dbtypes/model.go#L24

**Comment by chungisaac** [comment]
@Cjkjvfnby I've tried on Postman: PostModelOutputs uses user_unique_id and v2_user_unique_id

**Comment by nick-clarifai** [comment]
Hmm I tried doing PostModelOutputs on `distilbart-cnn-12-6` in dev on Postman and it said model not found. I also can't seem to find the model when I search for it in dev portal. Maybe resource syncing was incomplete? I'm not sure if the db entry gives any more clues as to why we're not seeing it.

**Review by nick-clarifai — APPROVED** [review]

**Pull request merged**
